#!/bin/sh
# chkconfig: 2345 10 90

prog=nvtd
binpath=/bin/$prog
pidfile=/tmp/run/"$prog".pid
wait_time=3

start()
{
	# check if synoaid is running.
	SYNOAID_PID=`pidof synoaid`
	if [ "$SYNOAID_PID" != "" ]; then
		echo "Stop synoaid"
		/etc/rc.d/init.d/synoaid stop
		sleep 1
	fi

	echo "Start $prog ..."
	args=""
	start-stop-daemon --start -n $prog --make-pidfile --pidfile $pidfile --exec $binpath -- $args &

	# start synoaid after starting nvtd
	SYNOAID_PID=`pidof synoaid`
	if [ "$SYNOAID_PID" == "" ]; then
		echo "Start synoaid"
		sleep 3 && /etc/rc.d/init.d/synoaid start &
	fi
}

stop()
{
	# stop synoaid before stopping nvtd
	SYNOAID_PID=`pidof synoaid`
	if [ "$SYNOAID_PID" != "" ]; then
		echo "Stop synoaid"
		/etc/rc.d/init.d/synoaid stop
		sleep 1
	fi

	echo "Stop $prog ..."
	start-stop-daemon --stop --quiet --signal SIGUSR2 -n $prog --exec $binpath --pidfile $pidfile

	# wait prog stop, kill it if timeout.
	while true
	do
		PROG_PID=`pidof $binpath`
		if [ "$PROG_PID" != "" ]; then
			if [ $wait_time -gt 0 ]; then
				echo "Wait $prog stop...$wait_time"
				let "wait_time--"
			else
				echo "Wait $prog stop...$wait_time, kill pid ($PROG_PID)!"
				killall -9 $binpath
				sleep 1
				break
			fi
			sleep 1
		else
			echo "Wait $prog stop done"
			break
		fi
	done
}

reload()
{
	echo "Reload $prog ..."
	start-stop-daemon --stop -n $prog --exec $binpath --pidfile $pidfile -s SIGHUP
}

restart()
{
	stop
	#sleep 1
	start
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		reload
		;;
	restart)
		restart
		;;
	*)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
